# Generated by Django 4.1 on 2022-09-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_examinations_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexaminationsrecords',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalexaminationsrecords',
            name='measurement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalexaminationstype',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
